import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class InterrupteurClient extends javax.swing.JFrame {

    /**
     * Creates new form InterrupteurClient
     */
    public InterrupteurClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interrupteur1 = new Interrupteur();
        interrupteur2 = new Interrupteur();
        interrupteur3 = new Interrupteur();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        interrupteur1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interrupteur1MouseClicked(evt);
            }
        });

        interrupteur2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interrupteur2MouseClicked(evt);
            }
        });

        interrupteur3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interrupteur3MouseClicked(evt);
            }
        });

        jLabel1.setText("Light 2");

        jLabel2.setText("Light 1");

        jLabel3.setText("Light 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(interrupteur3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interrupteur2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(interrupteur1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(interrupteur1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(interrupteur2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(interrupteur3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void interrupteur3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interrupteur3MouseClicked
         interrupteur3.addInterrupteurListener(new InterrupteurListener() {
             boolean statusEvent = false;
            @Override
            public void etatChange(InterrupteurEvent e) {
                statusEvent = e.getEtat();
                interrupteur3.setEtat(statusEvent);
            }
        });
            interrupteur3.change();
            interrupteur3.fireInterrupteurEvent(new InterrupteurEvent(interrupteur3.getEtat()));
            interrupteur3.repaint();    
            
            try {
            interrupteur3.lampeProxyRemote("lampe2",6060);
        } catch (RemoteException ex) {
            Logger.getLogger(WindowLampe2_3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_interrupteur3MouseClicked

    private void interrupteur1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interrupteur1MouseClicked
         interrupteur1.addInterrupteurListener(new InterrupteurListener() {
             boolean statusEvent = false;
            @Override
            public void etatChange(InterrupteurEvent e) {
                statusEvent = e.getEtat();
                interrupteur1.setEtat(statusEvent);
            }
        });
            interrupteur1.change();
            interrupteur1.fireInterrupteurEvent(new InterrupteurEvent(interrupteur1.getEtat()));
            interrupteur1.repaint();    
            
            try {
            interrupteur1.lampeProxyRemote("lampe1",7070);
        } catch (RemoteException ex) {
            Logger.getLogger(WindowLampe2_3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_interrupteur1MouseClicked

    private void interrupteur2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interrupteur2MouseClicked
         interrupteur2.addInterrupteurListener(new InterrupteurListener() {
             boolean statusEvent = false;
            @Override
            public void etatChange(InterrupteurEvent e) {
                statusEvent = e.getEtat();
                interrupteur2.setEtat(statusEvent);
            }
        });
            interrupteur2.change();
            interrupteur2.fireInterrupteurEvent(new InterrupteurEvent(interrupteur2.getEtat()));
            interrupteur2.repaint();    
            
            try {
            interrupteur2.lampeProxyRemote("lampe1",4040);
        } catch (RemoteException ex) {
            Logger.getLogger(WindowLampe2_3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_interrupteur2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterrupteurClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterrupteurClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterrupteurClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterrupteurClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterrupteurClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Interrupteur interrupteur1;
    private Interrupteur interrupteur2;
    private Interrupteur interrupteur3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
